{
 "title": "KubeDB / MySQL / Pod",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
   },
   {
    "name": "app",
    "label": "MySQL",
    "query": "label_values(kubedb_com_mysql_status_phase{namespace=~\"$namespace\"},app)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(mysql_up{namespace=~\"$namespace\", service=~\"$app+-stats\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "MySQL Pod Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "MySQL Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_version_info{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_buffer_pool_size{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\"}[5m])) by (pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(process_open_fds{pod=~\"$pod\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "MySQL Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Max Used Connects - {{pod}}"
    },
    {
     "expr": "mysql_global_variables_max_connections{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Max Connects - {{pod}}"
    }
   ]
  },
  {
   "title": "MySQL Aborted Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_aborted_connects{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Aborted Connects - {{pod}}"
    },
    {
     "expr": "mysql_global_status_aborted_clients{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Aborted Clients - {{pod}}"
    }
   ]
  },
  { "title": "Client Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "MySQL Client Thread Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Threads Connected - {{pod}}"
    },
    {
     "expr": "mysql_global_status_threads_running{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Threads Running - {{pod}}"
    }
   ]
  },
  {
   "title": "MySQL Thread Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_variables_thread_cache_size{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Thread Cache Size - {{pod}}"
    },
    {
     "expr": "mysql_global_status_threads_cached{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Threads Cached - {{pod}} "
    },
    {
     "expr": "mysql_global_status_threads_created{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Threads Created - {{pod}}"
    }
   ]
  },
  {
   "title": "Temporary Objects & Slow Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "MySQL Temporary Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_created_tmp_tables{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Created Tmp Tables - {{pod}}"
    },
    {
     "expr": "rate(mysql_global_status_created_tmp_disk_tables{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Created Tmp Disk Tables - {{pod}}"
    },
    {
     "expr": "mysql_global_status_created_tmp_files{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Created Tmp Files - {{pod}}"
    }
   ]
  },
  {
   "title": "MySQL Slow Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_slow_queries{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Slow Queries - {{pod}}"
    }
   ]
  },
  { "title": "Select Types and Sorts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "MySQL Select Types",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_select_full_join{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Select Full Join - {{pod}}"
    },
    {
     "expr": "rate(mysql_global_status_select_scan{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Select Scan - {{pod}}"
    }
   ]
  },
  {
   "title": "MySQL Sorts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_sort_rows{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Sort Rows - {{pod}}"
    },
    {
     "expr": "rate(mysql_global_status_sort_range{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Sort Range - {{pod}}"
    },
    {
     "expr": "rate(mysql_global_status_sort_merge_passes{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Sort Merge Passes - {{pod}}"
    },
    {
     "expr": "rate(mysql_global_status_sort_scan{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Sort Scan - {{pod}}"
    }
   ]
  },
  { "title": "Table Locks and Questions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "MySQL Table Locks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_table_locks_immediate{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Table Locks Immediate - {{pod}}"
    },
    {
     "expr": "rate(mysql_global_status_table_locks_waited{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Table Locks Waited - {{pod}}"
    }
   ]
  },
  {
   "title": "MySQL Questions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_questions{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Questions - {{pod}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "MySQL Network Traffic",
   "type": "graph",
   "description": "\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_received{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Inbound - {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_sent{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Outbound - {{pod}}"
    }
   ]
  },
  {
   "title": "MySQL Network Usage Hourly",
   "type": "graph",
   "description": "\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_bytes_received{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[1h])",
     "legendFormat": "Received - {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_bytes_sent{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[1h])",
     "legendFormat": "Sent - {{pod}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "MySQL Internal Memory Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_buffer_pool_size{namespace=\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "InnoDB Buffer Pool Size - {{pod}}"
    },
    {
     "expr": "mysql_global_variables_innodb_log_buffer_size{namespace=\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "InnoDB Log Buffer Size - {{pod}}"
    },
    {
     "expr": "mysql_global_status_innodb_mem_dictionary{namespace=\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "InnoDB Dictionary Size - {{pod}}"
    },
    {
     "expr": "mysql_global_variables_key_buffer_size{namespace=\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Key Buffer Size - {{pod}}"
    },
    {
     "expr": "mysql_global_variables_query_cache_size{namespace=\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Query Cache Size - {{pod}}"
    },
    {
     "expr": "mysql_global_status_innodb_mem_adaptive_hash{namespace=\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Adaptive Hash Index Size - {{pod}}"
    }
   ]
  },
  { "title": "Command, Handlers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Top Command Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(mysql_global_status_commands_total{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m]))",
     "legendFormat": "Com_{{ command }} - {{pod}}"
    }
   ]
  },
  {
   "title": "Top Command Counter Hourly",
   "type": "graph",
   "description": "\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, avg by (pod,command) (increase(mysql_global_status_commands_total{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[1h])>0))",
     "legendFormat": "Com_{{ command }} - {{pod}}"
    }
   ]
  },
  {
   "title": "MySQL Handlers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_handlers_total{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])>0",
     "legendFormat": "{{ handler }} - {{pod}}"
    }
   ]
  },
  { "title": "Query Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "MySQL Query Cache Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_qcache_free_memory{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Query Cache Size - {{pod}}"
    }
   ]
  },
  {
   "title": "MySQL Query Cache Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_qcache_hits{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Hits - {{pod}}"
    },
    {
     "expr": "rate(mysql_global_status_qcache_inserts{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Inserts - {{pod}}"
    },
    {
     "expr": "rate(mysql_global_status_qcache_not_cached{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Not Cached - {{pod}}"
    },
    {
     "expr": "rate(mysql_global_status_qcache_lowmem_prunes{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Prunes - {{pod}}"
    },
    {
     "expr": "rate(mysql_global_status_qcache_queries_in_cache{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Queries in Cache - {{pod}}"
    }
   ]
  },
  { "title": "Files and Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "MySQL File Openings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_opened_files{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Openings - {{pod}}"
    }
   ]
  },
  {
   "title": "MySQL Open Files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_open_files{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Open Files - {{pod}}"
    },
    {
     "expr": "mysql_global_variables_open_files_limit{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Open Files Limit - {{pod}}"
    },
    {
     "expr": "mysql_global_status_innodb_num_open_files{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "InnoDB Open Files - {{pod}}"
    }
   ]
  },
  {
   "title": "MySQL Table Openings and Definition Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 }
  },
  {
   "title": "MySQL Table Open Cache Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_opened_tables{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Openings - {{pod}}"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_hits{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Hits - {{pod}}"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_misses{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Misses - {{pod}}"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_overflows{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Misses due to Overflows - {{pod}}"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_hits{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Table Open Cache Hit Ratio - {{pod}}"
    }
   ]
  },
  {
   "title": "MySQL Open Tables",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_open_tables{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Open Tables - {{pod}}"
    },
    {
     "expr": "mysql_global_variables_table_open_cache{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Table Open Cache - {{pod}}"
    }
   ]
  },
  {
   "title": "MySQL Table Definition Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_open_table_definitions{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Open Table Definitions - {{pod}}"
    },
    {
     "expr": "mysql_global_variables_table_definition_cache{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Table Definitions Cache Size - {{pod}}"
    },
    {
     "expr": "mysql_global_status_opened_table_definitions{namespace=~\"$namespace\",service=~\"$app+-stats\",pod=~\"$pod\"}",
     "legendFormat": "Opened Table Definitions - {{pod}}"
    }
   ]
  }
 ]
}