{
 "title": "KubeDB / Kafka / Database",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "app",
    "label": "Kafka",
    "query": {
     "query": "label_values(kubedb_com_kafka_status_phase{namespace=~\"$namespace\"},app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kafka Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Status of Kafka Cluster",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_com_kafka_status_phase{namespace=\"$namespace\", app=\"$app\"} == 1"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Cluster Uptime",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{namespace=~\"$namespace\",pod=~\"$app-.+$\"}"
    }
   ]
  },
  {
   "title": "Controller Leader ID",
   "type": "stat",
   "description": "Current ID of the controller",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_current_leader{namespace=~\"$namespace\",pod=~\"$app.+$\"}"
    }
   ]
  },
  {
   "title": "Controller Leader",
   "type": "stat",
   "description": "Name of Controller leader",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{namespace=~\"$namespace\",pod=~\"$app.+$\"} == 1 "
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "description": "JVM version of the cluster",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(jvm_info{namespace=\"$namespace\", pod=~\"$app-.+$\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  { "title": "Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Global Topic count",
   "type": "table",
   "description": "The number of global topics as observed by this Controller.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globaltopiccount{namespace=\"$namespace\", pod=~\"$app-.+$\"}",
     "legendFormat": "{{ $pod }}"
    }
   ]
  },
  {
   "title": "Global Partition Count\t",
   "type": "table",
   "description": "The number of global partitions as observed by this Controller.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globalpartitioncount{namespace=\"$namespace\", pod=~\"$app-.+$\"}"
    }
   ]
  },
  {
   "title": "Offline Partition Count\t",
   "type": "table",
   "description": "The number of offline topic partitions (non-internal) as observed by this Controller.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount{namespace=\"$namespace\", pod=~\"$app-.+$\"}"
    }
   ]
  },
  {
   "title": "Preferred Replica Imbalance Count\t",
   "type": "table",
   "description": "The count of topic partitions for which the leader is not the preferred leader.\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_preferredreplicaimbalancecount{namespace=\"$namespace\", pod=~\"$app-.+$\"}"
    }
   ]
  },
  {
   "title": "Topic partition and replicas",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_cluster_partition_replicascount{namespace=\"$namespace\", pod=~\"$app-.+$\"}"
    }
   ]
  },
  {
   "title": "Underreplicated partitions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_cluster_partition_underreplicated{namespace=\"$namespace\", pod=~\"$app-.+$\"}"
    }
   ]
  },
  {
   "title": "Unknown Voter Connection",
   "type": "table",
   "description": "Number of unknown voter connection",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_number_unknown_voter_connections{namespace=~\"$namespace\",pod=~\"$app.+$\"}"
    }
   ]
  },
  {
   "title": "High Watermark",
   "type": "table",
   "description": "The high watermark maintained on a member; -1 if it is unknown.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_high_watermark{namespace=~\"$namespace\",pod=~\"$app.+$\"}"
    }
   ]
  },
  {
   "title": "Messages in topics",
   "type": "table",
   "description": "Incoming message rate per topic. Omitting 'topic=(...)' will yield the all-topic rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{namespace=\"$namespace\",pod=~\"$app-.+$\"}"
    }
   ]
  },
  {
   "title": "Fetch request rate",
   "type": "table",
   "description": "Fetch request (from clients or followers) rate per topic.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_totalfetchrequests_total{namespace=\"$namespace\",pod=~\"$app-.+$\"}"
    }
   ]
  },
  {
   "title": "First offset partitions",
   "type": "table",
   "description": "The first offset in a partition.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "kafka_log_log_logstartoffset{namespace=\"$namespace\",pod=~\"$app-.+$\"}"
    }
   ]
  },
  {
   "title": "Last offset partitions",
   "type": "table",
   "description": "The last offset in a partition.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "kafka_log_log_logendoffset{namespace=\"$namespace\",pod=~\"$app-.+$\"}"
    }
   ]
  },
  { "title": "I/O Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Disk read",
   "type": "graph",
   "description": "Linux disk reads in MiB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkaserver_linux_disk_read_bytes{namespace=~\"$namespace\",pod=~\"$app.+$\"} / 1024 /1024",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Disk writes",
   "type": "graph",
   "description": "Linux disk write in MiB",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkaserver_linux_disk_write_bytes{namespace=~\"$namespace\",pod=~\"$app.+$\"} / 1024 /1024",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Number of Messages",
   "type": "graph",
   "description": "Total number of messages per topic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{namespace=\"$namespace\", pod=~\"$app-.+$\", topic!~\"\"}",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Producer requests",
   "type": "graph",
   "description": "Producer request made in all the brokers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_totalproducerequests_total{namespace=\"$namespace\", pod=~\"$app-.+$\"} != 0",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Average Commit Latency",
   "type": "graph",
   "description": "The average time in milliseconds to commit an entry in the raft log.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_commit_latency_avg{namespace=~\"$namespace\",pod=~\"$app.+$\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Quorum Epoch",
   "type": "graph",
   "description": "The current quorum epoch.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_current_epoch{namespace=~\"$namespace\",pod=~\"$app.+$\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Byte in/out rate from clients",
   "type": "graph",
   "description": "Byte in/out (from the clients) rate per topic every 5m",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total{pod=~\"$app-.+$\",namespace=~\"$namespace\",topic!~\"\"}[5m])) by (topic)",
     "legendFormat": "{{ topic }} (in)"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesout_total{pod=~\"$app-.+$\",namespace=~\"$namespace\",topic!~\"\"}[5m])) by (topic)",
     "legendFormat": "{{ topic }} (out)"
    }
   ]
  },
  {
   "title": "The average fraction of time the request handler threads are idle",
   "type": "graph",
   "description": "between 0 and 1, ideally > 0.3",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkarequesthandlerpool_requesthandleravgidle_percent{namespace=\"$namespace\",pod=~\"$app-.+$\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Byte in/out total from clients",
   "type": "table",
   "description": "Byte in (from the clients) rate per topic. Omitting 'topic=(...)' will yield the all-topic rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesin_total{namespace=\"$namespace\",pod=~\"$app-.+$\"}"
    },
    {
     "expr": "kafka_server_brokertopicmetrics_bytesin_total{namespace=\"$namespace\",pod=~\"$app-.+$\"}"
    }
   ]
  },
  {
   "title": "Byte out rate to other brokers",
   "type": "table",
   "description": "Byte out (to the other brokers) rate per topic.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_replicationbytesout_total{namespace=\"$namespace\",pod=~\"$app-.+$\"}"
    }
   ]
  }
 ]
}