{
 "title": "KubeDB / Singlestore / Database",
 "tags": [ "singlestore" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "app",
    "label": "Singlestore",
    "query": {
     "query": "label_values(kubedb_com_singlestore_status_phase{namespace=~\"$namespace\"},app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "memsql_up{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "memsql_status_uptime{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(memsql_status_queries{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Singlestore Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memsql_status_max_used_connections{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "Current - {{ pod }}"
    },
    {
     "expr": "memsql_variable_max_connections{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "Max - {{ pod }}"
    }
   ]
  },
  {
   "title": "Singlestore  disk reads vs writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memsql_variable_load_data_read_size{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "reads - {{ pod }}"
    },
    {
     "expr": "memsql_variable_load_data_write_size{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "write - {{ pod }}"
    }
   ]
  },
  {
   "title": "Singlestore network received vs sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(memsql_status_bytes_received{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "received - {{ pod }}"
    },
    {
     "expr": "rate(memsql_status_bytes_sent{namespace=~\"$namespace\",service=~\"$app+-stats\"}[5m])",
     "legendFormat": "sent - {{ pod }}"
    }
   ]
  },
  {
   "title": "Alloc Databases List Entry",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memsql_status_alloc_databases_list_entry{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }} = '{{ command }}'"
    }
   ]
  },
  {
   "title": "Default Partitions Per Leaf",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memsql_variable_default_partitions_per_leaf{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Database Partitions Online",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memsql_distributed_partitions_total{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ database_name }}"
    }
   ]
  },
  {
   "title": "Database Partitions Offline",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memsql_distributed_partitions_offline{namespace=~\"$namespace\",service=~\"$app+-stats\"}",
     "legendFormat": "{{ database_name }}"
    }
   ]
  }
 ]
}