{
 "title": "KubeDb / Hazelcast / Database",
 "tags": [
  "kubedb",
  "database",
  "stats"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(kubedb_com_hazelcast_status_phase{namespace=~\"$namespace\"},app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Hazelcast Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Members",
   "type": "stat",
   "description": "Total number of active members",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(com_hazelcast_Metrics_activeMembers{namespace=~\"$namespace\",service=~\"$app-stats\"})",
     "legendFormat": "Member Count"
    }
   ]
  },
  {
   "title": "Cluster Uptime(minutes)",
   "type": "stat",
   "description": "Cluster Uptime in minutes",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(com_hazelcast_Metrics_uptime{namespace=~\"$namespace\",service=~\"$app-stats\"})/(1000*60)"
    }
   ]
  },
  {
   "title": "Client Count",
   "type": "stat",
   "description": "Total number of client",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(com_hazelcast_Metrics_clientCount{namespace=~\"$namespace\",service=\"$app-stats\"})",
     "legendFormat": "Client Count"
    }
   ]
  },
  {
   "title": "Partition counts",
   "type": "bargauge",
   "description": "Total Number of Partitions",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_activePartitionCount{namespace=~\"$namespace\",service=~\"$app-stats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Hazelcast Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "System Load",
   "type": "graph",
   "description": "System Load",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_systemLoadAverage{namespace=~\"$namespace\",service=~\"$app-stats\"}\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "description": "Heap Usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_usedHeap{namespace=~\"$namespace\",service=~\"$app-stats\"}/(com_hazelcast_Metrics_usedHeap{namespace=~\"$namespace\",service=~\"$app-stats\"}+com_hazelcast_Metrics_freeHeap{namespace=~\"$namespace\",service=~\"$app-stats\"})*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Owned Entry Memory Cost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryMemoryCost{namespace=~\"$namespace\",service=~\"$app-stats\"}/1000\n",
     "legendFormat": "{{pod}} {{tag0}}"
    }
   ]
  },
  {
   "title": "Backup Entry Memory Cost",
   "type": "graph",
   "description": "Backup Entry memory Cost",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_backupEntryMemoryCost{namespace=~\"$namespace\",service=~\"$app-stats\"}/1000\n",
     "legendFormat": "{{pod}} {{tag0}}"
    }
   ]
  },
  {
   "title": "Heap Cost",
   "type": "graph",
   "description": "Total Heap Cost",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_heapCost{namespace=~\"$namespace\",service=~\"$app-stats\"}/1000",
     "legendFormat": "{{pod}} {{tag0}}"
    }
   ]
  },
  { "title": "Hazelcast Operation Latency ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "GetLatency and GetCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalGetLatency{namespace=~\"$namespace\",service=~\"$app-stats\"}",
     "legendFormat": "GetLatency {{pod}} {{tag0}}"
    },
    {
     "expr": "com_hazelcast_Metrics_getCount{namespace=~\"$namespace\",service=~\"$app-stats\"}",
     "legendFormat": "GetCount {{pod}} {{tag0}}"
    }
   ]
  },
  {
   "title": "PutLatency and PutCount",
   "type": "graph",
   "description": "PutLatency and PutCount",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalPutLatency{namespace=~\"$namespace\",service=~\"$app-stats\"}",
     "legendFormat": "Put Latency {{pod}} {{tag0}}"
    },
    {
     "expr": "com_hazelcast_Metrics_putCount{namespace=~\"$namespace\",service=~\"$app-stats\"}\n",
     "legendFormat": "Put Count {{pod}} {{tag0}}"
    }
   ]
  },
  {
   "title": "SetLatency and SetCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalSetLatency{namespace=~\"$namespace\",service=~\"$app-stats\"}\n",
     "legendFormat": "setLatency {{pod}} {{tag0}}"
    },
    {
     "expr": "com_hazelcast_Metrics_setCount{namespace=~\"$namespace\",service=~\"$app-stats\"}\n",
     "legendFormat": "setCount {{pod}} {{tag0}}"
    }
   ]
  },
  {
   "title": "RemoveLatency and RemoveCount",
   "type": "graph",
   "description": "RemoveLatency and RemoveCount",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalRemoveLatency{namespace=~\"$namespace\",service=~\"$app-stats\"}",
     "legendFormat": "RemoveLatency {{pod}} {{tag0}}"
    },
    {
     "expr": "com_hazelcast_Metrics_removeCount{namespace=~\"$namespace\",service=~\"$app-stats\"}",
     "legendFormat": "RemoveCount {{pod}} {{tag0}}"
    }
   ]
  },
  {
   "title": "Entry Counts",
   "type": "graph",
   "description": "Entry Counts",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_entryCount{namespace=~\"$namespace\",service=~\"$app-stats\"}",
     "legendFormat": "{{pod}} {{tag0}}"
    }
   ]
  },
  {
   "title": "Backup Entry Count",
   "type": "graph",
   "description": "Backup Entry Count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_backupEntryCount{namespace=~\"$namespace\",service=~\"$app-stats\"}",
     "legendFormat": "{{pod}} {{tag0}}"
    }
   ]
  },
  {
   "title": "Locked Entry Count",
   "type": "graph",
   "description": "Locked Entry Count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_lockedEntryCount{namespace=~\"$namespace\",service=~\"$app-stats\"}\n",
     "legendFormat": "{{pod}} {{tag0}}"
    }
   ]
  },
  {
   "title": "Dirty Entry Count",
   "type": "graph",
   "description": "Dirty Entry Count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_dirtyEntryCount{namespace=~\"$namespace\",service=~\"$app-stats\"}\n",
     "legendFormat": "{{pod}} {{tag0}}"
    }
   ]
  }
 ]
}