{
 "title": "KubeDB / Hazelcast / Pod",
 "tags": [
  "kubedb",
  "pod",
  "stats"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(kubedb_com_hazelcast_status_phase{namespace=~\"$namespace\"},app)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(com_hazelcast_Metrics_activeMembers{namespace=\"$namespace\",pod=~\"$app.+$\"},pod)"
    }
   },
   {
    "name": "map",
    "query": {
     "query": "label_values(com_hazelcast_Metrics_ownedEntryCount{namespace=\"$namespace\",pod=~\"$app.+$\"},tag0)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Hazelcast memory Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Partition Counts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_activePartitionCount{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_systemLoadAverage{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\"}\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_usedHeap{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "com_hazelcast_Metrics_maxHeap{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Physical Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(com_hazelcast_Metrics_totalPhysicalMemorySize{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\"}-com_hazelcast_Metrics_freePhysicalMemorySize{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "com_hazelcast_Metrics_totalPhysicalMemorySize{namespace=~\"$namespace\",service=~\"$app-stats\",pod=~\"$pod\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_totalPhysicalMemorySize{namespace=\"$namespace\", service=~\"$app-stats\", pod=~\"$pod\"}) by (pod) - sum(com_hazelcast_Metrics_freePhysicalMemorySize{namespace=\"$namespace\", service=~\"$app-stats\", pod=~\"$pod\"}) by (pod) - sum(com_hazelcast_Metrics_committedHeap{namespace=\"$namespace\", service=~\"$app-stats\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_totalPhysicalMemorySize{namespace=\"$namespace\", service=~\"$app-stats\", pod=~\"$pod\"}) by (pod) - sum(com_hazelcast_Metrics_maxHeap{namespace=\"$namespace\", service=~\"$app-stats\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Free Physical Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_freePhysicalMemorySize{namespace=\"$namespace\", service=~\"$app-stats\", pod=~\"$pod\"} / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Non-heap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum(com_hazelcast_Metrics_totalPhysicalMemorySize{namespace=\"$namespace\", service=~\"$app-stats\", pod=~\"$pod\"}) by (pod) - sum(com_hazelcast_Metrics_freePhysicalMemorySize{namespace=\"$namespace\", service=~\"$app-stats\", pod=~\"$pod\"}) by (pod) - sum(com_hazelcast_Metrics_committedHeap{namespace=\"$namespace\", service=~\"$app-stats\", pod=~\"$pod\"}) by (pod) )",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min( sum(com_hazelcast_Metrics_totalPhysicalMemorySize{namespace=\"$namespace\", service=~\"$app-stats\", pod=~\"$pod\"}) by (pod) - sum(com_hazelcast_Metrics_maxHeap{namespace=\"$namespace\", service=~\"$app-stats\", pod=~\"$pod\"}) by (pod) )",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryMemoryCost{namespace=\"$namespace\", pod=~\"$pod\", service=~\"$app-stats\",tag0=~'$map'}",
     "legendFormat": "owned-entry-{{pod}}-{{tag0}}"
    },
    {
     "expr": "com_hazelcast_Metrics_backupEntryMemoryCost{namespace=\"$namespace\", pod=~\"$pod\", service=~\"$app-stats\",tag0=~'$map'}",
     "legendFormat": "backup-entry-{{pod}}-{{tag0}}"
    },
    {
     "expr": "com_hazelcast_Metrics_heapCost{namespace=\"$namespace\", pod=~\"$pod\", service=~\"$app-stats\",tag0=~'$map'}",
     "legendFormat": "heap-cost-{{pod}}-{{tag0}}"
    }
   ]
  },
  {
   "title": "Eviction Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_evictionCount{namespace=\"$namespace\", pod=~\"$pod\", service=~\"$app-stats\", tag0=~'$map'}",
     "legendFormat": "Owned entries: {{tag0}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Entry Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryCount{namespace=\"$namespace\", pod=~\"$pod\", service=~\"$app-stats\", tag0=~'$map'}",
     "legendFormat": "Owned entries: {{tag0}} - {{pod}}"
    },
    {
     "expr": "com_hazelcast_Metrics_backupEntryCount{namespace=\"$namespace\", pod=~\"$pod\", service=~\"$app-stats\", tag0=~'$map'}",
     "legendFormat": "Backup entries: {{tag0}} - {{pod}}"
    },
    {
     "expr": "com_hazelcast_Metrics_lockedEntryCount{namespace=\"$namespace\", pod=~\"$pod\", service=~\"$app-stats\", tag0=~'$map'}",
     "legendFormat": "Locked entries: {{tag0}} - {{pod}}"
    },
    {
     "expr": "com_hazelcast_Metrics_dirtyEntryCount{namespace=\"$namespace\", pod=~\"$pod\", service=~\"$app-stats\", tag0=~'$map'}",
     "legendFormat": "Dirty entries: {{tag0}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Hazelcast Operate Rate PerMinute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Put Rate Per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(com_hazelcast_Metrics_putCount{namespace=\"$namespace\", pod=~\"$pod\", service=~\"$app-stats\", tag0=~'$map'}[1m])",
     "legendFormat": "{{tag0}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Get Rate Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(com_hazelcast_Metrics_getCount{namespace=\"$namespace\", pod=~\"$pod\", service=~\"$app-stats\", tag0=~'$map'}[1m])",
     "legendFormat": "{{tag0}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Average get times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalGetLatency{namespace=\"$namespace\", pod=~\"$pod\", service=~\"$app-stats\", tag0=~'$map'} / ignoring(unit) com_hazelcast_Metrics_getCount{namespace=\"$namespace\", pod=~\"$pod\", service=~\"$app-stats\", tag0=~'$map'}",
     "legendFormat": "{{pod}} - {{tag0}}"
    }
   ]
  },
  {
   "title": "Remove Rate Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(com_hazelcast_Metrics_removeCount{namespace=\"$namespace\", pod=~\"$pod\", service=~\"$app-stats\", tag0=~'$map'}[1m])"
    }
   ]
  },
  {
   "title": "Average put times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalPutLatency{namespace=\"$namespace\", pod=~\"$pod\", service=~\"$app-stats\", tag0=~'$map'} / ignoring(unit) com_hazelcast_Metrics_putCount{namespace=\"$namespace\", pod=~\"$pod\", service=~\"$app-stats\", tag0=~'$map'}",
     "legendFormat": "{{pod}} - {{tag0}}"
    }
   ]
  },
  {
   "title": "Average Remove time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalRemoveLatency{namespace=\"$namespace\", pod=~\"$pod\", service=~\"$app-stats\", tag0=~'$map'} / ignoring(unit) com_hazelcast_Metrics_removeCount{namespace=\"$namespace\", pod=~\"$pod\", service=~\"$app-stats\", tag0=~'$map'}",
     "legendFormat": "{{pod}} - {{tag0}}"
    }
   ]
  }
 ]
}